/**
 * GENERATED by scripts/gen-skill-library.mjs from convex/skill-bodies/*.md.
 * Do NOT edit by hand — edit the .md body, then rerun the generator.
 */

export interface SkillLibrarySeed {
  slug: string;
  name: string;
  description: string;
  triggers: string[];
  body: string;
  origin: string;
  enabled: boolean;
}

export const CURATED: SkillLibrarySeed[] = [
  {
    slug: "brainstorm",
    name: "Brainstorm",
    description: "Use before any creative work - creating features, building components, adding functionality, or modifying behavior. Explores user intent, requirements and design before implementation.",
    triggers: ["brainstorm","idea","options","what if","decide between","choose"],
    origin: "anthropic",
    enabled: true,
    body: `# Brainstorming Ideas Into Designs

Help turn ideas into fully formed designs and specs through natural collaborative dialogue.

Start by classifying how much process the request needs, then work through your path: understand the context, refine the idea, present a design, and get your human partner's approval.

## Hard gate

Do NOT write any code, scaffold any project, or take any implementation action until you have told your human partner what you intend and they have approved it. The ceremony scales with the task; the approval gate never does.

## Three paths

Classify the request and say the classification out loud so your human partner can override it:

- **Spike** — a feasibility question whose output is an answer, not code you keep. Present the question and what you'll try in 2-3 sentences, get a nod, then find out as cheaply as correctness allows. Report findings as a recommendation; anything built stays labeled throwaway.
- **Bounded** — a well-scoped change to code that already exists: a new flag, a small endpoint, a one-file fix. Ask the clarifying questions that matter, present a short design in chat (a few sentences to a few short paragraphs), and STOP. Implementation starts only after your human partner says yes.
- **Architectural** — new projects, new subsystems, changes that restructure how components fit together. Questions, approaches, sectioned design, written spec, then a written implementation plan.

When in doubt between two paths, take the heavier one. Hidden complexity discovered mid-task upgrades the path — stop, say so, and step up.

## Anti-pattern: "too simple to need approval"

Every path ends with your human partner approving your intent before implementation. What scales with simplicity is the artifact, never the approval.

## Process

- Check current project state first (files, docs, recent commits).
- If the request spans multiple independent subsystems, flag it and help decompose before refining details.
- Ask questions one at a time: purpose, constraints, success criteria. Prefer multiple choice when possible.
- Propose 2-3 approaches with trade-offs; lead with your recommendation and reasoning. YAGNI ruthlessly.
- Present the design in sections scaled to complexity, checking after each section whether it looks right. Cover: architecture, components, data flow, error handling, testing.
- Design for isolation and clarity: small units, one clear purpose each, well-defined interfaces.

## Working in existing codebases

Explore the current structure before proposing changes and follow existing patterns. Include targeted improvements to code you're touching where they serve the current goal; don't propose unrelated refactoring.`,
  },
  {
    slug: "code-review",
    name: "Code Review",
    description: "Review code or diffs like Claude Code's Code Review pipeline — multi-agent style analysis for logic errors, security vulnerabilities, and regressions, with severity-tagged findings. Use when the user asks to review code, a diff, or a PR, or runs /code-review.",
    triggers: ["review","audit this","critique","code review","pr review"],
    origin: "anthropic",
    enabled: true,
    body: `# Code Review

Review the target code or diff the way Claude Code's Code Review does: a fleet of specialized passes over the changes in the context of the surrounding codebase, followed by a verification pass that filters false positives before reporting.

## What to check

Default focus is correctness — bugs that would break production, not formatting preferences or missing test coverage:

- Logic errors and broken edge cases
- Security vulnerabilities (injection, auth/authz gaps, unsafe handling of untrusted input)
- Subtle regressions against existing behavior
- Race conditions, error-handling gaps, incorrect boundary conditions
- If the repo has a CLAUDE.md: newly introduced violations of it are nit-level findings. If a REVIEW.md exists, its instructions are the highest-priority review guidance.

Expand scope only when the user asks (style, tests, docs).

## How to report

Tag every finding with severity:

| Marker | Severity | Meaning |
| ------ | -------- | ------- |
| 🔴 | Important | A bug that should be fixed before merging |
| 🟡 | Nit | A minor issue, worth fixing but not blocking |
| 🟣 | Pre-existing | A bug that exists in the codebase but was not introduced by this change |

For each finding:
- Point at the exact file:line and quote the offending code
- Explain the concrete failure — the input or flow that breaks, not a vibes-level concern
- Include a short "why this is real" verification note (you re-checked it against actual code behavior)
- Suggest the minimal fix

Order findings most-severe-first. If nothing is found, say so plainly and state what was reviewed. Do not pad with speculative nits. Do not modify code unless the user asks for fixes — review is read-only by default.`,
  },
  {
    slug: "deep-research",
    name: "Deep Research",
    description: "Systematic multi-angle web research instead of single superficial searches. Use for \"what is X\", \"explain X\", \"compare X and Y\", \"research X\", or before content generation that needs real-world information. A single search is never enough.",
    triggers: ["research","sources","compare","investigate","find out","deep dive"],
    origin: "anthropic",
    enabled: true,
    body: `# Deep Research

Systematic methodology for thorough web research. The quality of output depends on the quality and quantity of research — never generate content from general knowledge alone.

## Phase 1: Broad exploration

1. Initial survey searches to understand the overall landscape
2. Identify key subtopics, dimensions, and angles from the results
3. Map different perspectives and stakeholders

## Phase 2: Deep dive

For each important dimension:
1. Targeted searches with precise keywords, multiple phrasings
2. Read important sources in full, not just snippets
3. Follow references to other important resources

## Phase 3: Diversity & validation

| Information type | Purpose | Example |
|-----------------|---------|---------|
| Facts & data | Concrete evidence | "statistics", "market size" |
| Examples & cases | Real-world application | "case study", "implementation" |
| Expert opinions | Authority | "expert analysis", "interview" |
| Trends | Direction | "trends", "forecast" |
| Comparisons | Context | "vs", "alternatives" |
| Challenges | Balance | "limitations", "criticism" |

## Phase 4: Synthesis check — before writing, verify

- Searched from at least 3-5 different angles?
- Read the most important sources in full?
- Concrete data, examples, AND expert perspectives?
- Both positives and challenges covered?
- Information current and authoritative?

Any NO → keep researching.

## Search tips

- Be specific: "enterprise AI adoption trends 2026" not "AI trends"
- Hint authority: "research paper", "McKinsey report", "industry analysis"
- Always use the ACTUAL current date/year in temporal queries — never a hardcoded past year. "Latest/today" needs month+day precision.

## Quality bar

Research is sufficient when you can answer: key facts? 2-3 concrete examples? expert views? current trends? challenges? why relevant now?

## Common mistakes

- Stopping after 1-2 searches
- Relying on snippets without reading sources
- One angle on a multi-faceted topic
- Ignoring contradictions
- Outdated info when current data exists
- Generating content before research is complete`,
  },
  {
    slug: "frontend-design",
    name: "Frontend Design",
    description: "Guidance for distinctive, intentional visual design when building new UI or reshaping an existing one. Helps with aesthetic direction, typography, and making choices that don't read as templated defaults.",
    triggers: ["ui","interface","frontend","component","design","landing","dashboard"],
    origin: "anthropic",
    enabled: true,
    body: `# Frontend Design

Approach this as the design lead at a small studio known for giving every client a visual identity that could not be mistaken for anyone else's. This client has already rejected proposals that felt templated, and is paying for a distinctive point of view: make deliberate, opinionated choices about palette, typography, and layout that are specific to this brief, and take one real aesthetic risk you can justify.

## Ground it in the subject

If the brief does not pin down what the product or subject is, pin it yourself before designing: name one concrete subject, its audience, and the page's single job, and state your choice. If there's any information in your memory about the human's preferences, context about what they're building, or designs you've made before – use that as a hint. The subject's own world, its materials, instruments, artifacts, and vernacular, is where distinctive choices come from. Build with the brief's real content and subject matter throughout.

## Design principles

For web designs, the hero is a thesis. Open with the most characteristic thing in the subject's world, in whatever form makes sense for it: a headline, an image, an animation, a live demo, an interactive moment. Be deliberate with your choice: a big number with a small label, supporting stats, and a gradient accent is the template answer, only use if that's truly the best option.

Typography carries the personality of the page. Pair the display and body faces deliberately, not the same families you would reach for on any other project, and set a clear type scale with intentional weights, widths, and spacing. Make the type treatment itself a memorable part of the design, not a neutral delivery vehicle for the content.

Structure is information. Structural devices, numbering, eyebrows, dividers, labels, should encode something true about the content, not decorate it. Many generic designs use numbered markers (01 / 02 / 03), but that's only appropriate if the content actually is a sequence - like a real process or a typed timeline where order carries information the reader needs. Question if choices like numbered markers actually make sense before incorporating them.

Leverage motion deliberately. Think about where and if animation can serve the subject: a page-load sequence, a scroll-triggered reveal, hover micro-interactions, ambient atmosphere. An orchestrated moment usually lands harder than scattered effects; choose what the direction calls for. However, sometimes less is more, and extra animation contributes to the feeling that the design is AI-generated.

Match complexity to the vision. Maximalist directions need elaborate execution; minimal directions need precision in spacing, type, and detail. Elegance is executing the chosen vision well.

Consider written content carefully. Often a design brief may not contain real content, and it's up to you to come up with copy. Copy can make a design feel as templated as the design itself. See the below section on writing for more guidance.

## Process: brainstorm, explore, plan, critique, build, critique again

For calibration: AI-generated design right now clusters around three looks: (1) a warm cream background (near #F4F1EA) with a high-contrast serif display and a terracotta accent; (2) a near-black background with a single bright acid-green or vermilion accent; (3) a broadsheet-style layout with hairline rules, zero border-radius, and dense newspaper-like columns. All three are legitimate for some briefs, but they are defaults rather than choices, and they appear regardless of subject. Where the brief pins down a visual direction, follow it exactly — the brief's own words always win, including when it asks for one of these looks. Where it leaves an axis free, don't spend that freedom on one of these defaults. Just like a human designer who's hired, there's often a careful balance between doing what you're good at and taking each project as a chance to experiment and learn.

Work in two passes. First, brainstorm a short design plan based on the human's design brief: create a compact token system with color, type, layout, and signature. Color: describe the palette as 4–6 named hex values. Type: the typefaces for 2+ roles (a characterful display face that's used with restraint, a complementary body face, and a utility face for captions or data if needed). Layout: a layout concept, using one-sentence prose descriptions and ASCII wireframes to ideate and compare. Signature: the single unique element this page will be remembered by that embodies the brief in an appropriate way.

Then review that plan against the brief before building: if any part of it reads like the generic default you would produce for any similar page (work through a similar prompt to see if you arrive somewhere similar) rather than a choice made for this specific brief — revise that part, say what you changed and why. Only after you've confirmed the relative uniqueness of your design plan should you start to write the code, following the revised plan exactly and deriving every color and type decision from it.

When writing the code, be careful of structuring your CSS selector specificities. It's easy to generate CSS classes that cancel each other out (especially with a type-based selector like .section and a element-based selector like .cta). This can happen often with paddings/margins between sections.

Try to do a lot of this planning and iteration in your thinking, and only show ideas to the user when you have higher confidence it'll delight them.

## Restraint and self-critique

Spend your boldness in one place. Let the signature element be the one memorable thing, keep everything around it quiet and disciplined, and cut any decoration that does not serve the brief. Not taking a risk can be a risk itself! Build to a quality floor without announcing it: responsive down to mobile, visible keyboard focus, reduced motion respected. Critique your own work as you build, taking screenshots if your environment supports it – a picture is worth 1000 tokens. Consider Chanel's advice: before leaving the house, take a look in the mirror and remove one accessory. Human creators have memory and always try to do something new, so if you have a space to quickly jot down notes about what you've tried, it can help you in future passes.

## More on writing in design

Words appear in a design for one reason: to make it easier to understand, and therefore easier to use. They are design material, not decoration. Bring the same intentionality to copy that you would bring to spacing and color. Before writing anything, ask what the design needs to say, and how it can best be said to help the person navigate the experience.

Write from the end user's side of the screen. Name things by what people control and recognize, never by how the system is built. A person manages notifications, not webhook config. Describe what something does in plain terms rather than selling it. Being specific is always better than being clever.

Use active voice as default. A control should say exactly what happens when it's used: "Save changes," not "Submit." An action keeps the same name through the whole flow, so the button that says "Publish" produces a toast that says "Published." The vocabulary of an interface is the signposting for someone navigating the product. Cohesion and consistency are how people learn their way around.

Treat failure and emptiness as moments for direction, not mood. Explain what went wrong and how to fix it, in the interface's voice rather than a person's. Errors don't apologize, and they are never vague about what happened. An empty screen is an invitation to act.

Keep the register conversational and tuned: plain verbs, sentence case, no filler, with tone matched to the brand and the audience. Let each element do exactly one job. A label labels, an example demonstrates, and nothing quietly does double duty.`,
  },
  {
    slug: "security-review",
    name: "Security Review",
    description: "AI-powered security scanner that reasons about code like a security researcher — tracing data flows, catching injection flaws, auth bugs, exposed secrets, weak crypto. Use when asked to scan code for vulnerabilities, check for SQL injection/XSS/command injection, audit security, or run /security-review.",
    triggers: ["security","injection","xss","auth","hardening","owasp","exploit"],
    origin: "anthropic",
    enabled: true,
    body: `# Security Review

An AI-powered security scan that reasons about the codebase the way a human security researcher would — tracing data flows, understanding component interactions, and catching vulnerabilities pattern-matching tools miss.

## Workflow — follow in order

1. **Scope** — if a path was given, scan only that scope; else scan the whole project. Identify languages/frameworks (package.json, requirements.txt, go.mod, etc.).
2. **Dependency audit** — check manifests for known-vulnerable packages, deprecated crypto libs, suspiciously old pins.
3. **Secrets & exposure** — scan ALL files (config, env, CI, Dockerfiles) for hardcoded keys, tokens, private keys, committed .env files, connection strings with embedded credentials.
4. **Vulnerability deep scan** — reason, don't just pattern-match:
   - Injection: SQLi, XSS (unescaped output, dangerouslySetInnerHTML), command injection, header/log injection
   - Auth & access control: missing auth on sensitive endpoints, BOLA/IDOR, JWT weaknesses, CSRF, privilege escalation, mass assignment
   - Data handling: sensitive data in logs/errors/responses, missing encryption, path traversal, XXE, SSRF
   - Cryptography: MD5/SHA1/DES for security, hardcoded IVs, Math.random() for tokens, missing TLS validation
   - Business logic: TOCTOU races, integer overflow in money math, missing rate limiting, predictable resource IDs
5. **Cross-file data flow** — trace user-controlled input from entry points (params, headers, body, uploads) to sinks (queries, exec, HTML, file writes). Find what only appears across files.
6. **Self-verify** — for each finding, re-read with fresh eyes: is it actually exploitable, or did sanitization/framework handle it upstream? Downgrade or discard false positives.
7. **Report** — grouped by category, with severity and confidence per finding.
8. **Propose patches** — for CRITICAL and HIGH, show before/after with a concrete minimal fix. Never auto-apply: state "Review each patch before applying. Nothing has been changed yet."

## Severity

| Severity | Meaning |
|----------|---------|
| 🔴 CRITICAL | Immediate exploitation risk, data breach likely |
| 🟠 HIGH | Serious vulnerability, exploit path exists |
| 🟡 MEDIUM | Exploitable with conditions or chaining |
| 🔵 LOW | Best practice violation, low direct risk |
| ⚪ INFO | Observation, not a vulnerability |

## Output rules

- Lead with a findings summary table (counts by severity)
- Every finding: file path, line number, exact vulnerable snippet, plain-English risk (what could an attacker do?), confidence rating
- If clean, say so clearly with what was scanned
- Never auto-apply patches — present for human review only`,
  },
  {
    slug: "skill-creator",
    name: "Skill Creator",
    description: "Create new skills and modify or improve existing ones. Use when the user wants to create a skill from scratch, edit a skill, or improve a skill's description for better triggering accuracy.",
    triggers: ["create skill","new skill","improve skill","skill"],
    origin: "anthropic",
    enabled: true,
    body: `# Skill Creator

Create and iteratively improve skills. High level: understand intent → draft the skill → test with realistic prompts → evaluate with the user → rewrite → repeat until satisfied.

## Capture intent

1. What should this skill enable the model to do?
2. When should it trigger (phrases/contexts)?
3. Expected output format?
4. Do we need test cases? Skills with objectively verifiable outputs benefit; subjective ones (writing style, art) often don't.

If the current conversation already contains the workflow to capture, extract it from history first and confirm with the user.

## Writing the SKILL.md

Anatomy:

\`\`\`
skill-name/
├── SKILL.md (required)
│   ├── YAML frontmatter (name, description required)
│   └── Markdown instructions
└── Bundled resources (optional): scripts/ references/ assets/
\`\`\`

- **name**: identifier (kebab-case).
- **description**: the primary triggering mechanism — both what it does AND when to use it. Models under-trigger, so make it slightly pushy: name concrete contexts, not just the category.
- **body**: under ~500 lines; push detail into reference files with clear pointers. Prefer imperative form. Explain WHY instructions matter — smart models follow reasoning better than rigid MUSTs. Include input/output examples and exact output templates when format matters.

Progressive disclosure: metadata always in context (~100 words), body on trigger, bundled resources as needed.

## Evaluate and improve

1. Draft 2-3 realistic test prompts — what a real user would actually say. Share them before running.
2. Run the skill against them; capture outputs.
3. Have the user review qualitatively. For objective outputs, write programmatic checks.
4. Improve by generalizing from feedback — avoid overfit fiddly changes; if a stubborn issue persists, change the metaphor or working pattern rather than adding constraints.
5. Keep the prompt lean — remove anything not pulling its weight.
6. Repeat until the user is happy.

## Description optimization

When a skill under- or over-triggers, tune the description:
- Generate ~20 trigger eval queries (mix of should-trigger and near-miss should-not-trigger — realistic, concrete, with backstory, casual phrasing, typos).
- The best negative cases share keywords but need a different tool — not obviously irrelevant prompts.
- Iterate the description against this set; pick by held-out performance, not train.

## Rules

- Skills must not contain malware, exfiltration, or surprise behavior.
- When updating an existing skill, preserve its original name.`,
  },
];
