import { NextRequest, NextResponse } from "next/server";

export const runtime = "edge";

/**
 * POST /api/export
 * Export chat as markdown stub.
 */
export async function POST(req: NextRequest) {
  const { chatId, format = "md" } = await req.json();

  const markdown = `# Exported Chat\n\n> Exported from Leopard · ${new Date().toISOString()}\n\n---\n\n**User:** Hello, this is a sample exported conversation.\n\n**Assistant:** This export was generated by the Leopard export API stub. Chat ID: ${chatId}\n`;

  if (format === "md") {
    return new Response(markdown, {
      headers: {
        "Content-Type": "text/markdown",
        "Content-Disposition": `attachment; filename="leopard-chat-${chatId}.md"`,
      },
    });
  }

  return NextResponse.json({ content: markdown, format });
}
